### ISSUE TITLE
better / more consistent copy for stories?

### ISSUE THREAD

**Issue by russellsamora** [the-pudding/old-website#4]

**Comment by russellsamora** [comment]
* min / max character counts (could flag if wrong in sheet)
* formatting guidelines (eg. title case, periods for dek etc)

**Comment by jadiehm** [comment]
**Heds**
- Min: 15
- Max: 60
- Should be title case

**Deks**
- Min: 30
- Max: 80
- Should be sentence case
- If the dek is a full sentence it should end with punctuation
