### ISSUE TITLE
Non-editorial Link Hierarchy

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/old-website#62]
My tension is that the most prominent non-editorial links are:
- Join Newsletter Button
- Archives
- Topics
- About
- Social Links (top-left)

I *think* that the most important action is still Newsletter Button, but also that perhaps this could be converted to a input field to remove one more step. The next ones I think are Patreon and then Social Links. The Archives/Topics/About are lower in our desired reader behavior, especially assuming most people hitting the homepage are seeing it for the first time.

**Comment by russellsamora** [comment]
* discuss more by looking at data for newsletter (input vs. reveal input vs. link out)
* consider hamburger all the things and mobile (look at data)
