### ISSUE TITLE
author page is broken

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/old-website#79]
![Screen Shot 2019-04-18 at 9 23 13 AM](https://user-images.githubusercontent.com/2880174/56364024-9cdcb780-61bb-11e9-9f64-363be7ed0354.png)

**Comment by russellsamora** [comment]
Not a bug, bad instructions :)

Updated [here](https://github.com/the-pudding/FYI/wiki/Publishing-New-Story)

> If there is a new author, add their image to dev/common/assets/authors.

**Comment by matthewfdaniels** [comment]
LOL
